name: Check JVM
on: [ push ]
jobs:
  JVM-Run-Gradle-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Build kaff4
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: check buildHealth --continue

      - name: Verify build health
        run: |
          BUILD_HEALTH_REPORT="./build/reports/dependency-analysis/build-health-report.txt"
          
          if [ -s $BUILD_HEALTH_REPORT ]; then
            echo "Failed: ./gradlew buildHealth"
            echo ""
            cat $BUILD_HEALTH_REPORT
            exit 1
          fi

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-reports
          path: ./**/build/reports/
